language: c
group: travis_latest
dist: xenial

before_install:
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -q
  - sudo apt-get install octave liboctave-dev -y
  - pip install --user --upgrade pip
  - pip install --user jupyter
  - pip install --user octave_kernel 

addons:
  apt:
    packages:
    - octave
    - liboctave-dev

matrix:
  include:
  - os: linux
  
script:
- octave-cli tests/installpkgs.m
- octave-cli tests/pom-test.m
- cd notebooks 
- python test_notebooks.py
